#!/usr/bin/env python3

import requests

people = requests.get('http://api.open-notify.org/astros.json')
print(people.text)

people_json = people.json()
print(people_json)
print(people_json['message'])

for p in people_json['people']:
    print(p['name'])
